/**
 * channel_binding.cpp — Host-side file-mapping channel bindings.
 *
 * Exports (registered in addon.cpp):
 *   openChannel(name: string)  → ArrayBuffer (mapped view, CHANNEL_BYTE_SIZE bytes)
 *   closeChannel(name: string) → undefined
 *   readChannelView(name: string) → ArrayBuffer | null
 *   writeCommand(name: string, transformBytes: Float32Array(12), scaleBytes: Float32Array(3), flags?: number) → undefined
 *
 * CHANNEL OWNERSHIP (Scheme A — locked in 03-03/03-04):
 *   The HOST creates the named memory-backed page (host side, before inject).
 *   The agent opens the same name via OpenFileMappingA.
 *   Naming: "Local\\SwgToolkitLive_<uuid-fragment>" — generated by JS caller
 *   BEFORE LaunchAndInjectWorker is constructed (pid not known until after launch).
 *
 * BUFFER MODEL (05-13 gap — Electron 42 V8 sandbox):
 *   Electron 42's V8 memory sandbox FORBIDS external ArrayBuffers (a buffer whose
 *   backing store points at foreign memory) — napi_create_external_arraybuffer
 *   throws "External buffers are not allowed", which killed openChannel outright
 *   (the Phase-3 design wrapped the mapped view directly). Fix: the JS-facing
 *   ArrayBuffer is now a normal V8-OWNED buffer (sandbox-legal — the same pattern
 *   native-core already uses everywhere). The mapped view is a SEPARATE raw
 *   pointer held in ChannelState; readChannelView COPIES the view into the owned
 *   buffer each call (a seqlock-validated 400-byte memcpy — trivial cost), and
 *   writeCommand writes to the raw view directly. The owned buffer is plain GC
 *   (no finalizer); the view is released explicitly by cleanupChannel.
 *
 * CROSS-PROCESS NOTE (RESEARCH.md §Pitfall 4):
 *   V8 SAB cannot cross OS process boundaries ("could not be cloned").
 *   The file-mapping IS the cross-process hop; the ArrayBuffer here is the
 *   renderer-side JS surface only — never use SAB across processes.
 *
 * CHANNEL LAYOUT (05-01 ROUND 5, 400 bytes total — see packages/contracts/src/live-inject.ts):
 *   [0..319]   read frame (agent-written every tick — SEQ_COUNTER/TRANSFORM/NETWORK_ID/
 *              TEMPLATE_NAME/LIVENESS), unchanged since Phase 3.
 *   [320..323] FOCUS_TOKEN — agent-authoritative, part of the read frame. Read-only here.
 *   [324..391] command region — writeCommand's ENTIRE write span (seqlock LONG at 324,
 *              cmdTransform 328-375, cmdScale 376-387, cmdFlags 388-391).
 *   [392..395] GUARD_STATUS — agent-authoritative. Read-only here.
 *   [396..399] GUARD_ADDR — agent-authoritative. Read-only here.
 *   writeCommand NEVER touches offsets 320-323 or 392-399 — those three fields are
 *   written exclusively by the agent (channel.cpp's channelWrite / channelWriteGuardStatus).
 */

#include <napi.h>
#include <Windows.h>
#include <string>
#include <unordered_map>
#include <cstring>
#include <cstdlib>   // _strtoui64 (decimal u64 building id)

// Channel byte size — matches LIVE_CHANNEL_TOTAL_SIZE (@swg/contracts) AND the agent's
// sizeof(LiveState). Grown from the original 400-byte frame to 1308 to append the
// decoration-persist region (CAPTURE @400 + REBIND @1024 + RESULT @1300 — model D). The
// CAPTURE + RESULT spans ride along in readChannelView's whole-view copy, so the renderer
// parses them with the same seqlock idiom it uses for the read frame; only the host->agent
// REBIND write needs its own N-API method (writeRebind, added with the host wiring step).
static constexpr size_t CHANNEL_BYTE_SIZE = 1308;

// ---------------------------------------------------------------------------
// Per-channel state.
//   view  — the raw mapped-view pointer (the cross-process shared memory). Read
//           AND write go through this. Released explicitly by cleanupChannel.
//   abRef — a persistent V8-OWNED ArrayBuffer (refcount=1). readChannelView
//           copies `view` into it and returns the SAME object every call, so the
//           renderer's identity-keyed region-view cache stays valid.
// ---------------------------------------------------------------------------

struct ChannelState {
    HANDLE hMap = nullptr;
    void*  view = nullptr;   // mapped view; owned here, unmapped in cleanupChannel
    // JS-facing copy target — a V8-owned buffer, NOT an external wrap of `view`
    // (Electron 42 sandbox forbids external buffers). Persistent so the returned
    // object identity is stable across readChannelView calls.
    Napi::Reference<Napi::ArrayBuffer> abRef;
};

static std::unordered_map<std::string, ChannelState> s_channels;

// ---------------------------------------------------------------------------
// cleanupChannel — release the copy buffer, unmap the view, close the handle.
// The view is unmapped here explicitly (the owned ArrayBuffer no longer carries a
// finalizer). Unmap before CloseHandle; the OS keeps the mapping object alive
// while a view is open, so either order is safe, but unmap-first is clearest.
// ---------------------------------------------------------------------------

static void cleanupChannel(const std::string& name) {
    auto it = s_channels.find(name);
    if (it == s_channels.end()) return;

    ChannelState& cs = it->second;
    cs.abRef.Reset();                 // release the V8-owned copy buffer (plain GC)
    if (cs.view) {                    // we own the view now (no finalizer) — unmap it
        UnmapViewOfFile(cs.view);
        cs.view = nullptr;
    }
    if (cs.hMap) {
        CloseHandle(cs.hMap);
        cs.hMap = nullptr;
    }
    s_channels.erase(it);
}

// ---------------------------------------------------------------------------
// OpenChannel
//
// openChannel(name: string) → ArrayBuffer
//
// Creates the named memory-backed mapping (host side, before inject).
// The agent opens the same name via OpenFileMappingA in agent_init.
// ---------------------------------------------------------------------------

Napi::Value OpenChannel(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 1 || !info[0].IsString()) {
        Napi::TypeError::New(env, "openChannel: (name: string) required")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }
    const std::string name = info[0].As<Napi::String>().Utf8Value();

    // Idempotent re-open: clean up any prior channel with this name.
    cleanupChannel(name);

    // Host creates the mapping (INVALID_HANDLE_VALUE = memory-backed, no disk file).
    // Named so the agent can open it via OpenFileMappingA with the same name.
    HANDLE hMap = CreateFileMappingA(
        INVALID_HANDLE_VALUE,
        nullptr,
        PAGE_READWRITE,
        0,
        static_cast<DWORD>(CHANNEL_BYTE_SIZE),
        name.c_str()
    );
    if (!hMap) {
        Napi::Error::New(env,
            "openChannel: CreateFileMappingA failed (name=" + name +
            " error=" + std::to_string(GetLastError()) + ")")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }

    void* view = MapViewOfFile(hMap, FILE_MAP_READ | FILE_MAP_WRITE,
                               0, 0, CHANNEL_BYTE_SIZE);
    if (!view) {
        CloseHandle(hMap);
        Napi::Error::New(env, "openChannel: MapViewOfFile failed")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }

    // Zero-initialize the view (clean initial state for the seqlock reader).
    std::memset(view, 0, CHANNEL_BYTE_SIZE);

    // JS-facing buffer: a V8-OWNED ArrayBuffer (Electron 42's sandbox forbids
    // external buffers). readChannelView copies `view` into this each call, and
    // returns it by identity every time so the renderer's region-view cache stays
    // valid. Seed it with the (zeroed) initial snapshot.
    auto ab = Napi::ArrayBuffer::New(env, CHANNEL_BYTE_SIZE);
    std::memcpy(ab.Data(), view, CHANNEL_BYTE_SIZE);

    ChannelState cs;
    cs.hMap  = hMap;
    cs.view  = view;
    cs.abRef = Napi::Reference<Napi::ArrayBuffer>::New(ab, 1);
    s_channels.emplace(name, std::move(cs));

    return ab;
}

// ---------------------------------------------------------------------------
// CloseChannel — release the GC guard and close the mapping handle.
// ---------------------------------------------------------------------------

Napi::Value CloseChannel(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 1 || !info[0].IsString()) {
        Napi::TypeError::New(env, "closeChannel: (name: string) required")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }
    cleanupChannel(info[0].As<Napi::String>().Utf8Value());
    return env.Undefined();
}

// ---------------------------------------------------------------------------
// ReadChannelView — snapshot the mapped view into the owned buffer and return it.
// Returns null if the channel is not open.
//
// The copy is seqlock-validated on the read-frame counter (SEQ_COUNTER, offset 0,
// agent-written): read the counter, memcpy 400 bytes, re-read the counter; retry
// (bounded) if the counter was odd (writer mid-write) or changed (torn). This
// reproduces, in native code, the tear-free guarantee the old design got for free
// from JS reading live memory — a plain snapshot could otherwise freeze a torn
// frame past the JS seqlock. On the rare exhaustion the copied counter is forced
// odd so parseChannelView rejects the frame (skipped frame, never a torn accept).
// ---------------------------------------------------------------------------

Napi::Value ReadChannelView(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 1 || !info[0].IsString()) {
        Napi::TypeError::New(env, "readChannelView: (name: string) required")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }
    const std::string name = info[0].As<Napi::String>().Utf8Value();

    auto it = s_channels.find(name);
    if (it == s_channels.end() || it->second.view == nullptr || it->second.abRef.IsEmpty()) {
        return env.Null();
    }

    char* dst = static_cast<char*>(it->second.abRef.Value().Data());
    const char* src = static_cast<const char*>(it->second.view);
    volatile const LONG* seqPtr = reinterpret_cast<volatile const LONG*>(src); // SEQ_COUNTER @ 0

    constexpr int kMaxAttempts = 8;
    bool clean = false;
    for (int attempt = 0; attempt < kMaxAttempts; ++attempt) {
        const LONG s1 = *seqPtr;
        if (s1 & 1) continue;                   // writer mid-write — retry
        MemoryBarrier();
        std::memcpy(dst, src, CHANNEL_BYTE_SIZE);
        MemoryBarrier();
        const LONG s2 = *seqPtr;
        if (s1 == s2) { clean = true; break; }  // stable, untorn snapshot
    }
    if (!clean) {
        // Couldn't capture a stable read-frame in kMaxAttempts (effectively never
        // at 30-60fps writes vs. a sub-microsecond copy). Force the copied
        // SEQ_COUNTER odd so parseChannelView rejects it rather than risk a torn
        // accept — the renderer simply skips this frame.
        *reinterpret_cast<LONG*>(dst) |= 1;
    }

    return it->second.abRef.Value();
}

// ---------------------------------------------------------------------------
// WriteCommand — host writes a target transform/scale into the command region.
//
// writeCommand(name: string, transformBytes: Float32Array(12), scaleBytes: Float32Array(3), flags?: number) → undefined
//
// Writes into the SAME named mapping openChannel already created — no second
// CreateFileMappingA call. Seqlock write spans EXACTLY offsets 324-391
// (cmdSeqCounter/cmdTransform/cmdScale/cmdFlags). Offsets 320-323 (FOCUS_TOKEN)
// and 392-399 (GUARD_STATUS/GUARD_ADDR) are agent-authoritative and are NEVER
// written here — mirrors the agent's own channelWrite increment-write-increment
// shape (channel.cpp), just run from the host side at the command-slot offset.
// ---------------------------------------------------------------------------

Napi::Value WriteCommand(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 3 || !info[0].IsString()) {
        Napi::TypeError::New(env,
            "writeCommand: (name: string, transformBytes: Float32Array(12), "
            "scaleBytes: Float32Array(3), flags?: number) required")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }
    const std::string name = info[0].As<Napi::String>().Utf8Value();

    // --- Validate transform (info[1]): must be exactly 12 floats / 48 bytes. ---
    if (!info[1].IsTypedArray() && !info[1].IsArrayBuffer()) {
        Napi::TypeError::New(env, "writeCommand: transformBytes must be a Float32Array or ArrayBuffer")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }
    const void* transformData = nullptr;
    size_t transformByteLength = 0;
    if (info[1].IsTypedArray()) {
        Napi::TypedArray ta = info[1].As<Napi::TypedArray>();
        transformData = static_cast<const char*>(ta.ArrayBuffer().Data()) + ta.ByteOffset();
        transformByteLength = ta.ByteLength();
    } else {
        Napi::ArrayBuffer ab = info[1].As<Napi::ArrayBuffer>();
        transformData = ab.Data();
        transformByteLength = ab.ByteLength();
    }
    if (transformByteLength != 48) {
        Napi::RangeError::New(env,
            "writeCommand: transformBytes must be exactly 12 floats (48 bytes)")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }

    // --- Validate scale (info[2]): must be exactly 3 floats / 12 bytes. ---
    if (!info[2].IsTypedArray() && !info[2].IsArrayBuffer()) {
        Napi::TypeError::New(env, "writeCommand: scaleBytes must be a Float32Array or ArrayBuffer")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }
    const void* scaleData = nullptr;
    size_t scaleByteLength = 0;
    if (info[2].IsTypedArray()) {
        Napi::TypedArray ta = info[2].As<Napi::TypedArray>();
        scaleData = static_cast<const char*>(ta.ArrayBuffer().Data()) + ta.ByteOffset();
        scaleByteLength = ta.ByteLength();
    } else {
        Napi::ArrayBuffer ab = info[2].As<Napi::ArrayBuffer>();
        scaleData = ab.Data();
        scaleByteLength = ab.ByteLength();
    }
    if (scaleByteLength != 12) {
        Napi::RangeError::New(env,
            "writeCommand: scaleBytes must be exactly 3 floats (12 bytes)")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }

    // --- flags (info[3]): optional, defaults to 0. ---
    uint32_t flags = 0;
    if (info.Length() >= 4 && !info[3].IsUndefined() && !info[3].IsNull()) {
        if (!info[3].IsNumber()) {
            Napi::TypeError::New(env, "writeCommand: flags must be a number")
                .ThrowAsJavaScriptException();
            return env.Undefined();
        }
        flags = static_cast<uint32_t>(info[3].As<Napi::Number>().Uint32Value());
    }

    // --- Look up the channel — reuse the existing s_channels map (no second registry). ---
    auto it = s_channels.find(name);
    if (it == s_channels.end() || it->second.view == nullptr) {
        Napi::Error::New(env, "writeCommand: channel not open — call openChannel first")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }

    // Write to the RAW mapped view (the cross-process shared memory), NOT the
    // V8-owned copy buffer — the agent reads the command region from the mapping.
    char* view = static_cast<char*>(it->second.view);

    // Seqlock write at offset 324 — spans EXACTLY the command region (324-391).
    // FOCUS_TOKEN (320-323), GUARD_STATUS (392-395), and GUARD_ADDR (396-399) are
    // agent-authoritative and are NEVER touched here.
    volatile LONG* cmdSeq = reinterpret_cast<volatile LONG*>(view + 324);

    InterlockedIncrement(cmdSeq);                       // seq → odd: write in progress
    std::memcpy(view + 328, transformData, 48);          // COMMAND_TRANSFORM
    std::memcpy(view + 376, scaleData, 12);               // COMMAND_SCALE
    std::memcpy(view + 388, &flags, 4);                    // COMMAND_FLAGS
    InterlockedIncrement(cmdSeq);                       // seq → even: write complete

    return env.Undefined();
}

// ---------------------------------------------------------------------------
// writeRebind(name, epoch, buildingId, derivedTemplate, flags) → undefined
//   Host → agent decoration REBIND (model D). Seqlock write of the REBIND region
//   (offsets 1024-1299), the answer to a CAPTURE the agent published. buildingId is a
//   DECIMAL u64 STRING (JS numbers can't hold a full 64-bit id losslessly). The agent
//   applies each new epoch once (wsSetNodeTemplateName + wsSaveSnapshot).
// ---------------------------------------------------------------------------
Napi::Value WriteRebind(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    if (info.Length() < 5 || !info[0].IsString() || !info[1].IsNumber() ||
        !info[2].IsString() || !info[3].IsString() || !info[4].IsNumber()) {
        Napi::TypeError::New(env,
            "writeRebind: (name: string, epoch: number, buildingId: string, "
            "derivedTemplate: string, flags: number) required")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }

    const std::string name    = info[0].As<Napi::String>().Utf8Value();
    const uint32_t    epoch   = info[1].As<Napi::Number>().Uint32Value();
    const std::string idStr   = info[2].As<Napi::String>().Utf8Value();
    const std::string tmpl    = info[3].As<Napi::String>().Utf8Value();
    const uint32_t    flags   = info[4].As<Napi::Number>().Uint32Value();

    const uint64_t buildingId = _strtoui64(idStr.c_str(), nullptr, 10);  // 0 on garbage → agent refuses

    auto it = s_channels.find(name);
    if (it == s_channels.end() || it->second.view == nullptr) {
        Napi::Error::New(env, "writeRebind: channel not open — call openChannel first")
            .ThrowAsJavaScriptException();
        return env.Undefined();
    }

    char* view = static_cast<char*>(it->second.view);

    // Seqlock write at offset 1024 — spans the REBIND region (1024-1299). RESULT (1300-1307)
    // is agent-authoritative and never touched here.
    volatile LONG* rebindSeq = reinterpret_cast<volatile LONG*>(view + 1024);

    InterlockedIncrement(rebindSeq);                    // seq → odd: write in progress
    std::memcpy(view + 1028, &epoch, 4);                 // REBIND_EPOCH
    std::memcpy(view + 1032, &flags, 4);                 // REBIND_FLAGS
    std::memcpy(view + 1036, &buildingId, 8);            // REBIND_BUILDING_ID
    // REBIND_DERIVED_TEMPLATE (1044, 256 bytes) — zero-fill then copy (guaranteed NUL-terminated).
    std::memset(view + 1044, 0, 256);
    std::memcpy(view + 1044, tmpl.c_str(), tmpl.size() < 255 ? tmpl.size() : 255);
    InterlockedIncrement(rebindSeq);                    // seq → even: write complete

    return env.Undefined();
}
