/**
 * packages/renderer/src/hooks/useLiveService.ts
 * Plain async functions (NOT a React hook) that bridge UI attach intent to
 * the native addon and route results to liveStore actions.
 *
 * Four exports:
 *   getAgentDllPath()          — resolves the canonical agent DLL path (dev vs packaged)
 *   prepareAgentDllForInject() — copies it to a uniquely-named temp file per inject
 *   launchAndInjectUI()        — launch + inject path (primary, D-02)
 *   attachToRunningUI()        — attach-to-running path (secondary, D-02)
 *
 * Phase 3 is READ-VERIFY ONLY. Neither function has any write path.
 * No useEffect — plain async functions so button handlers can await them.
 *
 * Source: 03-06b-PLAN.md Task 1; 03-CONTEXT.md §D-01, §D-02, §D-08.
 * Naming scheme A (locked — 03-05 Task 1): mappingName generated by host
 * before openChannel + launchAndInject so both receive the same name.
 */

import path from 'path';
import fs from 'fs';
import os from 'os';
import { useLiveStore } from '../state/liveStore';

// Path B: require the addon directly (nodeIntegration:true in the renderer).
// Mirrors the pattern used by @swg/native-core throughout the renderer.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const addon = require('@swg/live-inject') as {
  openChannel:     (name: string) => ArrayBuffer;
  launchAndInject: (clientExe: string, agentDll: string, mappingName: string) => Promise<{ pid: number }>;
  attachAndInject: (pid: number, agentDll: string, mappingName: string) => Promise<{ pid: number }>;
  readChannelView: (name: string) => ArrayBuffer | null;
};

// ─── Agent DLL path ───────────────────────────────────────────────────────────

/**
 * Returns the absolute path to the injected agent DLL.
 * Selects the dev build path or the packaged resource path based on
 * app.isPackaged from electron.
 */
export function getAgentDllPath(): string {
  let isPackaged = false;
  try {
    // app is main-process; renderer accesses it via the electron bridge
    // (nodeIntegration:true, contextIsolation:false). Falls back to false on error.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { app } = require('electron') as { app: { isPackaged: boolean } };
    isPackaged = app.isPackaged;
  } catch {
    isPackaged = false;
  }

  if (isPackaged) {
    return path.join(process.resourcesPath, 'agent', 'swg_toolkit_agent.dll');
  }
  return path.join(
    __dirname,
    '../../packages/live-inject/agent/build-agent/Release/swg_toolkit_agent.dll',
  );
}

/**
 * Copies the canonical agent DLL to a uniquely-named temp file and returns that
 * path, so every inject loads FRESH code.
 *
 * Why this is required (verified in Phase-03 live UAT — see STATE.md):
 * LoadLibraryA matches an already-resident module by basename and just bumps its
 * refcount. Injecting the fixed-name build output means a re-attach (or a rebuilt
 * DLL) silently re-runs the OLD agent already mapped in the client, and the loaded
 * file stays locked — blocking the next agent rebuild. A unique basename per inject
 * sidesteps both. The agent reads only the mapping name passed to it, so the file
 * name is free to vary.
 *
 * Best-effort: prunes prior copies that are no longer locked (a still-mapped copy
 * in a live client throws on unlink — left for the OS to reclaim). On copy failure
 * it falls back to the canonical path so the inject still attempts.
 */
export function prepareAgentDllForInject(): string {
  const canonical = getAgentDllPath();
  const dir = path.join(os.tmpdir(), 'swg-toolkit-agent');
  try {
    fs.mkdirSync(dir, { recursive: true });
    for (const f of fs.readdirSync(dir)) {
      if (f.startsWith('agent-') && f.endsWith('.dll')) {
        try { fs.unlinkSync(path.join(dir, f)); } catch { /* still mapped in a live client — leave it */ }
      }
    }
    const unique = `agent-${Date.now()}-${process.pid}-${Math.random().toString(36).slice(2, 8)}.dll`;
    const dest = path.join(dir, unique);
    fs.copyFileSync(canonical, dest);
    return dest;
  } catch {
    return canonical;
  }
}

// ─── Launch & Inject (primary path) ──────────────────────────────────────────

/**
 * Launch the SWG client exe and inject the agent DLL (D-02 primary path).
 *
 * 1. Generate mappingName (Scheme A — host generates before constructing worker).
 * 2. beginAttach() → transitions store status to 'connecting'.
 * 3. addon.openChannel(mappingName) — creates the file-mapping (synchronous).
 * 4. addon.launchAndInject(clientExe, agentDll, mappingName) — async.
 *    On resolve → attachComplete(pid, mappingName).
 *    On reject  → attachError(reason); 'file-patch mode' substring in reason
 *                 causes D-08 fallback via the error path (no special branching
 *                 needed — attachError always sets mode='file-patch').
 *
 * Phase 3 READ-VERIFY ONLY — no write path.
 */
export async function launchAndInjectUI(clientExe: string): Promise<void> {
  // Scheme A: host generates mapping name; both openChannel and launchAndInject receive it.
  const mappingName = 'Local\\SwgToolkitLive_' + Math.random().toString(36).slice(2, 10);

  useLiveStore.getState().beginAttach(clientExe);

  try {
    addon.openChannel(mappingName);
  } catch (e) {
    const err = e as Error;
    useLiveStore.getState().attachError('Channel open failed: ' + (err?.message ?? String(e)));
    return;
  }

  const agentDll = prepareAgentDllForInject();

  try {
    const result = await addon.launchAndInject(clientExe, agentDll, mappingName);
    useLiveStore.getState().attachComplete(result.pid, mappingName);
  } catch (err) {
    const reason = String((err as Error)?.message ?? err);
    useLiveStore.getState().attachError(reason);
  }
}

// ─── Attach to Running (secondary path) ──────────────────────────────────────

/**
 * Attach to an already-running SWG client process by PID (D-02 secondary path).
 * Same channel/mapping generation pattern as launchAndInjectUI.
 *
 * On ACCESS_DENIED → attachError(reason) → D-08 file-patch fallback (T-03-05).
 * Phase 3 READ-VERIFY ONLY — no write path.
 */
export async function attachToRunningUI(pid: number): Promise<void> {
  const mappingName = 'Local\\SwgToolkitLive_' + Math.random().toString(36).slice(2, 10);

  useLiveStore.getState().beginAttach(String(pid));

  try {
    addon.openChannel(mappingName);
  } catch (e) {
    const err = e as Error;
    useLiveStore.getState().attachError('Channel open failed: ' + (err?.message ?? String(e)));
    return;
  }

  const agentDll = prepareAgentDllForInject();

  try {
    const result = await addon.attachAndInject(pid, agentDll, mappingName);
    useLiveStore.getState().attachComplete(result.pid, mappingName);
  } catch (err) {
    const reason = String((err as Error)?.message ?? err);
    useLiveStore.getState().attachError(reason);
  }
}
